### ISSUE TITLE
Return &Path instead of PathBuf.

### ISSUE THREAD

**Issue by hch12907** [tbu-/dirs#4]
`dirs` clones and returns `PathBuf` when the functions of `Directories` (such as `config_home`) are called. Personally I think it would be nice if `&Path` is returned instead. 

Users, for times, don't actually require the ownership of the `Path` nor mutating it. If they want the ownership, they can simply call `.to_path_buf()` (which clones the `Path` anyways).

If every single call of the function clones the PathBuf, some performance penalties (although marginal) will occur.

(by the way, all the issues submitted by me have their respective code written at my fork: [hch12907/dirs](https://github.com/hch12907/dirs))

**Comment by tbu-** [comment]
Do you want to make pull requests for these features?
